### ISSUE TITLE
General converter exception

### ISSUE THREAD

**Issue by chococlat** [deefrawley/Flow.Launcher.Plugin.GenConvert#11]
After installing the extension, and typing `gc`, i get this error:
```
Please open new issue in: https://github.com/deefrawley/Flow.Launcher.Plugin.GenConvert/issues/new
1. upload log file: C:\Users\cecco\AppData\Roaming\FlowLauncher\Logs\1.9.5\2022-10-07.txt
2. copy below exception message

Flow Launcher version: 1.9.5
OS Version: Microsoft Windows NT 10.0.22621.0
IntPtr Length: 8
x64: True

Python Path: 
Date: 10/07/2022 15:25:42
Exception:
General Converter Exception: 
Websites: https://github.com/deefrawley/Flow.Launcher.Plugin.GenConvert
Author: deefrawley
Version: 1.1.2
Flow.Launcher.Core.ExternalPlugins.FlowPluginException: Access is denied.
 ---> System.ComponentModel.Win32Exception (5): Access is denied.
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 247
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.QueryAsync(Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 322
   at Flow.Launcher.Core.Plugin.PluginManager.<>c__DisplayClass22_0.<<QueryForPluginAsync>b__0>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 191
--- End of stack trace from previous location ---
   at Flow.Launcher.Infrastructure.Stopwatch.DebugAsync(String message, Func`1 action) in C:\projects\flow-launcher\Flow.Launcher.Infrastructure\Stopwatch.cs:line 34
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 190
   --- End of inner exception stack trace ---
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 210
   at Flow.Launcher.ViewModel.MainViewModel.<>c__DisplayClass137_0.<<QueryResults>g__QueryTask|2>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 616
--- End of stack trace from previous location ---
   at Flow.Launcher.ViewModel.MainViewModel.QueryResults() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 590
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__140_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

I'm attaching also the log file 2022-10-07.txt
[2022-10-07.txt](https://github.com/deefrawley/Flow.Launcher.Plugin.GenConvert/files/9734278/2022-10-07.txt)
The last fatality is the one im talking about

**Comment by deefrawley** [comment]
Do other plugins work ok?

**Comment by chococlat** [comment]
Actually they dont. I sent the same issue also to them and to the main
flowlayncher repo.


Il sab 8 ott 2022, 02:58 Damien ***@***.***> ha scritto:

**Comment by deefrawley** [comment]
Looks like a core code issue as the Access Denied error happens there first. Will let the team sort it out there.

**Comment by jjw24** [comment]
Just for troubleshooting, can you switch flow to portable mode and see if you still get the error.

If still getting the error, move flow to desktop (while still in portable mode).

Basically trying to see if it is related to user account access rights to Flow's location.

**Comment by deefrawley** [comment]
I'm closing this issue as it should be resolved in the general linked issue
