### ISSUE TITLE
AttributeError

### ISSUE THREAD

**Issue by TruongNGM** [deefrawley/Flow.Launcher.Plugin.GenConvert#25]
Please type any relevant information here

<details open><summary>Trace Log</summary>
<p>

```
Traceback (most recent call last):
  File "C:\Users\TruongN\AppData\Roaming\FlowLauncher\Plugins\General Converter-2.0.1\plugin\general_converter.py", line 63, in query
    do_convert = gen_convert(float(args[0]), args[1], args[2])
                             ^^^^^^^^^^^^^^
ValueError: could not convert string to float: '25lb'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\TruongN\AppData\Roaming\FlowLauncher\Plugins\General Converter-2.0.1\lib\flox\launcher.py", line 44, in run
    results = request_method(*request_parameters) or self._results
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\TruongN\AppData\Roaming\FlowLauncher\Plugins\General Converter-2.0.1\lib\flox\__init__.py", line 132, in _query
    self.query(query)
  File "C:\Users\TruongN\AppData\Roaming\FlowLauncher\Plugins\General Converter-2.0.1\plugin\general_converter.py", line 95, in query
    self.add_item(title="Error - {}").format(repr(e), subtitle="")
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'dict' object has no attribute 'format'

```
</p>
</details>

**Comment by deefrawley** [comment]
You need a space between the amount and the source, but I also need to trap this error and handle it better.
